name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "./scripts/build.sh"
  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./scripts/build.sh
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: dist/darwin-amd64
